Fix mismatched hash when reparsing
Issue: CCMDEVEXEC-1940

json.load() of Python 3.5 may not load json file in a deterministic way,
so ignoring value of SPDX_LICENSE_DATA when calculating its signature.

Fixing errors similar to the following ones:

ERROR: When reparsing .../layers/oe-core/meta/recipes-devtools/perl/perl-native_5.22.1.bb.do_create_spdx,
the basehash value changed from 89c07ab3c85c31b2c7d681f72584928e to a3652ea3ba79cadf6d446754e44b2aa7.
The metadata is not deterministic and this needs to be fixed.

Signed-off-by: Dang Libin <libin.dang@windriver.com>